name: Test FastAPI app
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test application
        run: pytest src/tests.py

  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run linter
        run: flake8 src

  run-project:
    runs-on: ubuntu-latest
    needs:
      - run-tests
      - run-linter
    steps:
      - name: Run project
        run: echo I am simulating running the project